name = "zetaidx-price-worker"
main = "src/index.ts"
compatibility_date = "2024-04-02"

[[kv_namespaces]]
binding = "PRICE_CACHE"
id = "cbf56dfece2d46798510ccdf89019cfb"

[build]
command = "npm run build" 

[triggers]
crons = [ "*/3 * * * *"]